//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ClientesReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tarjetas", Namespace="http://schemas.datacontract.org/2004/07/ML.Entities")]
    [System.SerializableAttribute()]
    public partial class Tarjetas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.ClientesReference.Clientes ClientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTarjetasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.ClientesReference.Clientes Clientes {
            get {
                return this.ClientesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientesField, value) != true)) {
                    this.ClientesField = value;
                    this.RaisePropertyChanged("Clientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTarjetas {
            get {
                return this.IdTarjetasField;
            }
            set {
                if ((this.IdTarjetasField.Equals(value) != true)) {
                    this.IdTarjetasField = value;
                    this.RaisePropertyChanged("IdTarjetas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nip {
            get {
                return this.NipField;
            }
            set {
                if ((this.NipField.Equals(value) != true)) {
                    this.NipField = value;
                    this.RaisePropertyChanged("Nip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoCuenta {
            get {
                return this.NoCuentaField;
            }
            set {
                if ((this.NoCuentaField.Equals(value) != true)) {
                    this.NoCuentaField = value;
                    this.RaisePropertyChanged("NoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoTarjeta {
            get {
                return this.NoTarjetaField;
            }
            set {
                if ((this.NoTarjetaField.Equals(value) != true)) {
                    this.NoTarjetaField = value;
                    this.RaisePropertyChanged("NoTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clientes", Namespace="http://schemas.datacontract.org/2004/07/ML.Entities")]
    [System.SerializableAttribute()]
    public partial class Clientes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amaterno {
            get {
                return this.AmaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.AmaternoField, value) != true)) {
                    this.AmaternoField = value;
                    this.RaisePropertyChanged("Amaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apaterno {
            get {
                return this.ApaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApaternoField, value) != true)) {
                    this.ApaternoField = value;
                    this.RaisePropertyChanged("Apaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdClientes {
            get {
                return this.IdClientesField;
            }
            set {
                if ((this.IdClientesField.Equals(value) != true)) {
                    this.IdClientesField = value;
                    this.RaisePropertyChanged("IdClientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientesResponse", Namespace="http://schemas.datacontract.org/2004/07/SL")]
    [System.SerializableAttribute()]
    public partial class ClientesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.ClientesReference.Clientes[] ClientesListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.ClientesReference.Clientes[] ClientesList {
            get {
                return this.ClientesListField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientesListField, value) != true)) {
                    this.ClientesListField = value;
                    this.RaisePropertyChanged("ClientesList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientesReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTarjeta", ReplyAction="http://tempuri.org/IService1/GetTarjetaResponse")]
        PL.ClientesReference.ClientesResponse GetTarjeta(PL.ClientesReference.Tarjetas tarjetas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTarjeta", ReplyAction="http://tempuri.org/IService1/GetTarjetaResponse")]
        System.Threading.Tasks.Task<PL.ClientesReference.ClientesResponse> GetTarjetaAsync(PL.ClientesReference.Tarjetas tarjetas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PL.ClientesReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PL.ClientesReference.IService1>, PL.ClientesReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL.ClientesReference.ClientesResponse GetTarjeta(PL.ClientesReference.Tarjetas tarjetas) {
            return base.Channel.GetTarjeta(tarjetas);
        }
        
        public System.Threading.Tasks.Task<PL.ClientesReference.ClientesResponse> GetTarjetaAsync(PL.ClientesReference.Tarjetas tarjetas) {
            return base.Channel.GetTarjetaAsync(tarjetas);
        }
    }
}
